### PR TITLE
Remove rgdal dependency

### LINKED ISSUE #17: dependency on rgdal
:wave: @cvitolo! this package uses rgdal that has been retired from CRAN.

Are you still able to maintain rdefra? I have a vague memory of our trying to find new maintainers?

### PR DESCRIPTION
**Pull request by olivroy**
Not sure I can be the maintainer as I did not understand how the source website may have evolved and what the expected results are. The tests and examples are lacking a little. I haven't gone through the article and vignette however.

However, I was able to fix #17 easily (the package doesn't seem to be using any rgdal functions)

I added a few refactoring here and there that may open the way to updating the package.

### CODE REVIEW

**Comment by maelle** [comment]
oh I had missed this @olivroy sorry! Do you want write access?

**Comment by maelle** [comment]
Thanks so much :pray:

**Comment by olivroy** [comment]
@maelle Sure

**Comment by maelle** [comment]
@olivroy sent you an invitation to the GitHub organization, and a team with admin access. 

Can you send me your email address so we can invite you to rOpenSci slack workspace? 

You're not forced to become a maintainer, but it's better you get the actual experience before you make a decision. :innocent:

**Comment by olivroy** [comment]
Sure! Are we good with merging this first?

**Comment by maelle** [comment]
You can merge this PR, unless you want me to review first? In which case I'd have a look next week.

**Comment by maelle** [comment]
@olivroy 

Can you send me your email address so we can invite you to rOpenSci slack workspace?

**Comment by olivroy** [comment]
olivierroy71@hotmail.com

**Comment by maelle** [comment]
Invite sent!

**Pull request merged**
